### ISSUE TITLE
unusual animating

### ISSUE THREAD

**Issue by iTofu** [yeatse/KingfisherWebP#39]
Hi, I have a problem, I try to using a webp image, but it plays very slowly. It happends when I using KingfisherWebP, it works fine on Chrome brower. So could you please take a look at it for me? Thanks:)

This WebP file:
[test.webp.zip](https://github.com/Yeatse/KingfisherWebP/files/5028064/test.webp.zip)

**Comment by iTofu** [comment]
目前发现当 WebP 带类似空白帧的间隔时，稳定出现。大概是：
```
（△：帧）
△1-----△2------------------------△3

△1：动画开始
△2：动画结束
△3：空白动作，以实现间隔效果
```
这种效果的 WebP 使用 KingfisherWebP 显示异常，而 [SDWebImage](https://github.com/SDWebImage/SDWebImageWebPCoder) 和 Chrome 显示正常。猜测应该是解码那块有点问题？

**Comment by Yeatse** [comment]
Due to the limitations of Kingfisher itself, the frame duration of a third party animated image can only be equally divided. The UIImage API just has a duration param for all the frames ([Apple documentation](https://developer.apple.com/documentation/uikit/uiimage/1624149-animatedimage)). But we are still working on to solve it. Any PR is also welcome.

**Comment by dreampiggy** [comment]
Learn hack code from SDWebImage for suck UIImage animation design:

https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Core/SDImageCoderHelper.m#L59

Tip: Repeat specify frames multiple times to make duration works. Calculate the Greatest common divisor to solve the issue.

But to say, it's bad on performance. Kingfisher should better provide the generic version of that `GIFAnimatedImage` class. Like SDWebImage's advanced custom `Animated Image Class` featurfe here: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-image-50
